### ISSUE TITLE
[BUG] Blank screen when opening the manager

### ISSUE THREAD

**Issue by HRDU** [MSFS-Mega-Pack/MSFS2020-livery-manager#146] opened 2020-10-26 20:52 UTC
## Description

Blank screen when opening the manager. Some UI Elements appear only for a brief second when opening the app.

## To reproduce

1. Install the Manager
2. Open the manager.

## Environment

**Manager version:** Liveries_Mega_Pack_Manager-0.2.2

**FS2020 Version:** n/a

## Screenshots or videos

![image](https://user-images.githubusercontent.com/32091326/97226926-6387fd80-17dd-11eb-969d-c039ec9c846e.png)

**Comment by davwheat** [comment] 2020-10-26 20:59
Invalid. Duplicate of #138. Please see the steps to fix this error in that issue.

**Closed** 2020-10-26 20:59 UTC
Labels: duplicate, invalid

**Comment by HRDU** [comment] 2020-10-26 21:17
> Invalid. Duplicate of #138. Please see the steps to fix this error in that issue.

Thank's, I've followed the steps from #138 and it fixed my issue.
Here's some additional info that might help you in the feature with this bug.
The `Community folder` was not created, but it was automatically identified by the manager. I went and created it manually in the game folder and everything works.

**Comment by davwheat** [comment] 2020-10-26 22:03
OH MY GOD IS THAT ACTUALLY THE REASON? THANK YOUUUU
